# -*- coding: utf-8 -*-
"""aula 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jI01UilSrHPfGx_xK9KWlElEuq-LizNH
"""



var = "texto" #string
var = 1 #inteiro
var = 1.1 #flaot
var = True #booleano
var = {1,2,3} # set
var = {"a": 1, "b": 2, "c": 3} # dicionario
var = [1,2,3] # lista
var = (1,2,3) # tupla: é uma lista que não pode ser modificada 
var = """ texto em docstring""" #docstring
type(var)
dir(var)

# Isso é um comentario 
""" Isso é uma docstring """

lista = [1,2,3] # funciona o append()
"""lista = (1,2,3) # não funciona o append()"""
lista1 = (3,4,5)
lista.append('giovane')

lista2 = []
for i in lista1:
  lista2.append(i)
lista2

#exemplo de nome de varialvel
x ="comum"
_x = "privada de classe"
XX = "constante"

#exemplo de metodo 
#meu_metodo()
#exemplo de classe 
#MinhaClasse()

time = input("qual o melhor time do Brasil ?")
var2 = "time"
print("o melhor time do Brasil é o",time) 
# ou
print("o melhor {} do brasil é o {}".format(var2,time))
#ou
print("o melhor {b} do brasil é o {a}".format(a=time,b=var2))
#ou
var = f"O melhor {var2} do Brasil é o {time}"
print(var)

#EXEMPLO DE QUERY 
#selecionar = "SELECT * FROM {tabela} WHERE dado={valor}".format(tabela=tabela_banco, valor=input)

help(x)

# print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)
print("A","motivação","é","uma","decisão","depende","de","si","mesmo " ,sep=".")